import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import ResNav from "./Components/ResNav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-inter">
        <Navbar />
        <ResNav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
